<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    ...
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Management" Version="9.0.9" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="9.0.9" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\Driver\WinUsbControlSigning.cer">
      <LogicalName>iPhoneUsbShare.Driver.WinUsbControlSigning.cer</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>