name: Build AppleNcm driver
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Build AppleNcm
        shell: powershell
        run: .\Driver\build-driver.ps1
      - name: Upload driver artifact
        uses: actions/upload-artifact@v4
        with:
          name: AppleNcm-x64
          path: Driver\artifacts\AppleNcm\**
